# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

l3solver <- function(Umat, Vmat, Amat, bvec) {
    .Call(`_L3solver_l3solver`, Umat, Vmat, Amat, bvec)
}

