# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

l3solver_ <- function(Xmat, Amat, bvec, Umat, Vmat, Smat, Tmat, tau, max_iter, tol, verbose = FALSE) {
    .Call(`_L3solver_l3solver`, Xmat, Amat, bvec, Umat, Vmat, Smat, Tmat, tau, max_iter, tol, verbose)
}

